#
# For more information see https://github.com/bbatsov/rubocop/blob/master/config/default.yml
#
# However, do not include entire blocks here just because you want to change them.
# Include only the specific lines that you're changing from the defaults.
#
AllCops:
  TargetRubyVersion: 2.1

Style/IfUnlessModifier:
  MaxLineLength: 100
Style/WhileUntilModifier:
  MaxLineLength: 100
Metrics/LineLength:
  Max: 100
Style/BracesAroundHashParameters:
  Enabled: false
Style/ClassCheck:
  Enabled: false
Style/DotPosition:
  EnforcedStyle: leading
Style/IndentHash:
  EnforcedStyle: consistent
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/BlockDelimiters:
  EnforcedStyle: semantic
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/SymbolArray:
  Enabled: true
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
